#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

compton --config /home/i686/.config/compton/comptonrc &
# feh --bg-fill /home/i686/Pictures/Wallpapers/01.png &
feh --randomize --bg-fill ~/Pictures/Wallpapers
# wmname LG3D &
~/.bin/launch_polybar.sh &
xautolock -time 5 -locker 'i3lock-fancy -f Hack Nerd -- scrot -z' &
#killall mate-notification-daemon; dunst &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nemo state=floating follow=on 
bspc rule -a Firefox state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
